---
vulkan_packages:
  - libvulkan1
  - mesa-vulkan-drivers
  - vulkan-tools

vulkan_update_cache: true
vulkan_apt_cache_valid_time: 3600

vulkan_icd_dir: /usr/share/vulkan/icd.d
vulkan_override_icd_filenames: ""
vulkan_layer_path: ""
