---
slurm_inventory_group: rocks
slurm_controller_host: rock0

slurm_cluster_name: sbcc
slurm_partition_name: compute
slurm_partition_max_time: INFINITE
slurm_include_controller_in_partition: true

slurm_user: slurm
slurm_real_memory_pct: 95
slurm_default_cpus: 4
slurm_default_mem_mb: 1024
slurmctld_port: 6817
slurmd_port: 6818

slurm_conf_path: /etc/slurm/slurm.conf
slurm_munge_key_path: /etc/munge/munge.key
slurm_state_save_location: /var/spool/slurmctld #controller node
slurm_slurmd_spool_dir: /var/spool/slurmd #compute node
slurm_log_dir: /var/log/slurm

slurm_run_slurmd_on_controller: true

slurm_common_packages:
  - munge
  - slurm-client
  - slurmd

slurm_controller_packages:
  - slurmctld
